# Generated by Django 5.2.1 on 2025-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='participant_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
